/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HostRouteImport } from './routes/_host'
import { Route as GameRouteImport } from './routes/_game'
import { Route as HostIndexRouteImport } from './routes/_host.index'
import { Route as HostGamesRouteImport } from './routes/_host.games'
import { Route as HostLDeckIdRouteImport } from './routes/_host.l.$deckId'
import { Route as HostDDeckIdRouteImport } from './routes/_host.d.$deckId'
import { Route as GamePCodeRouteImport } from './routes/_game.p.$code'
import { Route as GameGCodeRouteImport } from './routes/_game.g.$code'
import { Route as GameGCodeIndexRouteImport } from './routes/_game.g.$code.index'
import { Route as GameGCodePlayRouteImport } from './routes/_game.g.$code.play'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/_host',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const HostGamesRoute = HostGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => HostRoute,
} as any)
const HostLDeckIdRoute = HostLDeckIdRouteImport.update({
  id: '/l/$deckId',
  path: '/l/$deckId',
  getParentRoute: () => HostRoute,
} as any)
const HostDDeckIdRoute = HostDDeckIdRouteImport.update({
  id: '/d/$deckId',
  path: '/d/$deckId',
  getParentRoute: () => HostRoute,
} as any)
const GamePCodeRoute = GamePCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => GameRoute,
} as any)
const GameGCodeRoute = GameGCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => GameRoute,
} as any)
const GameGCodeIndexRoute = GameGCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameGCodeRoute,
} as any)
const GameGCodePlayRoute = GameGCodePlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GameGCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HostIndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/games': typeof HostGamesRoute
  '/g/$code': typeof GameGCodeRouteWithChildren
  '/p/$code': typeof GamePCodeRoute
  '/d/$deckId': typeof HostDDeckIdRoute
  '/l/$deckId': typeof HostLDeckIdRoute
  '/g/$code/play': typeof GameGCodePlayRoute
  '/g/$code/': typeof GameGCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HostIndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/games': typeof HostGamesRoute
  '/p/$code': typeof GamePCodeRoute
  '/d/$deckId': typeof HostDDeckIdRoute
  '/l/$deckId': typeof HostLDeckIdRoute
  '/g/$code/play': typeof GameGCodePlayRoute
  '/g/$code': typeof GameGCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_game': typeof GameRouteWithChildren
  '/_host': typeof HostRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_host/games': typeof HostGamesRoute
  '/_host/': typeof HostIndexRoute
  '/_game/g/$code': typeof GameGCodeRouteWithChildren
  '/_game/p/$code': typeof GamePCodeRoute
  '/_host/d/$deckId': typeof HostDDeckIdRoute
  '/_host/l/$deckId': typeof HostLDeckIdRoute
  '/_game/g/$code/play': typeof GameGCodePlayRoute
  '/_game/g/$code/': typeof GameGCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/games'
    | '/g/$code'
    | '/p/$code'
    | '/d/$deckId'
    | '/l/$deckId'
    | '/g/$code/play'
    | '/g/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/games'
    | '/p/$code'
    | '/d/$deckId'
    | '/l/$deckId'
    | '/g/$code/play'
    | '/g/$code'
  id:
    | '__root__'
    | '/_game'
    | '/_host'
    | '/join'
    | '/login'
    | '/_host/games'
    | '/_host/'
    | '/_game/g/$code'
    | '/_game/p/$code'
    | '/_host/d/$deckId'
    | '/_host/l/$deckId'
    | '/_game/g/$code/play'
    | '/_game/g/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GameRoute: typeof GameRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_host': {
      id: '/_host'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_host/': {
      id: '/_host/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/_host/games': {
      id: '/_host/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof HostGamesRouteImport
      parentRoute: typeof HostRoute
    }
    '/_host/l/$deckId': {
      id: '/_host/l/$deckId'
      path: '/l/$deckId'
      fullPath: '/l/$deckId'
      preLoaderRoute: typeof HostLDeckIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/_host/d/$deckId': {
      id: '/_host/d/$deckId'
      path: '/d/$deckId'
      fullPath: '/d/$deckId'
      preLoaderRoute: typeof HostDDeckIdRouteImport
      parentRoute: typeof HostRoute
    }
    '/_game/p/$code': {
      id: '/_game/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof GamePCodeRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/g/$code': {
      id: '/_game/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GameGCodeRouteImport
      parentRoute: typeof GameRoute
    }
    '/_game/g/$code/': {
      id: '/_game/g/$code/'
      path: '/'
      fullPath: '/g/$code/'
      preLoaderRoute: typeof GameGCodeIndexRouteImport
      parentRoute: typeof GameGCodeRoute
    }
    '/_game/g/$code/play': {
      id: '/_game/g/$code/play'
      path: '/play'
      fullPath: '/g/$code/play'
      preLoaderRoute: typeof GameGCodePlayRouteImport
      parentRoute: typeof GameGCodeRoute
    }
  }
}

interface GameGCodeRouteChildren {
  GameGCodePlayRoute: typeof GameGCodePlayRoute
  GameGCodeIndexRoute: typeof GameGCodeIndexRoute
}

const GameGCodeRouteChildren: GameGCodeRouteChildren = {
  GameGCodePlayRoute: GameGCodePlayRoute,
  GameGCodeIndexRoute: GameGCodeIndexRoute,
}

const GameGCodeRouteWithChildren = GameGCodeRoute._addFileChildren(
  GameGCodeRouteChildren,
)

interface GameRouteChildren {
  GameGCodeRoute: typeof GameGCodeRouteWithChildren
  GamePCodeRoute: typeof GamePCodeRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameGCodeRoute: GameGCodeRouteWithChildren,
  GamePCodeRoute: GamePCodeRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface HostRouteChildren {
  HostGamesRoute: typeof HostGamesRoute
  HostIndexRoute: typeof HostIndexRoute
  HostDDeckIdRoute: typeof HostDDeckIdRoute
  HostLDeckIdRoute: typeof HostLDeckIdRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostGamesRoute: HostGamesRoute,
  HostIndexRoute: HostIndexRoute,
  HostDDeckIdRoute: HostDDeckIdRoute,
  HostLDeckIdRoute: HostLDeckIdRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GameRoute: GameRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
